apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    name: client
spec:
  replicas: 3
  selector:
    matchLabels:
      name: client
  template:
    metadata:
      labels:
        name: client
    spec:
      containers:
        - name: client
          image: csmiles/webclientperf:client
          ports:
            - containerPort: 8180